"""nullable True

Revision ID: 002bbe6dd9fd
Revises: 44c00ecb7a4d
Create Date: 2024-12-31 15:25:16.611279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002bbe6dd9fd'
down_revision: Union[str, None] = '44c00ecb7a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'annotation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'annotation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
