"""Addition genre, piblisher

Revision ID: 31e84a719552
Revises: 6be724caf510
Create Date: 2024-12-30 20:21:37.632590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e84a719552'
down_revision: Union[str, None] = '6be724caf510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=False))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
